name: Java CI

on: [push]

jobs:
  test:
    name: Test on Java ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8, 11]
    steps:
    - uses: actions/checkout@v1
    - name: Use Java ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: mvn testing
      run: ./mvnw test -B
